TRUNCATE TABLE BRONZE.CRM_CUST_INFO 
BULK INSERT BRONZE.CRM_CUST_INFO 
FROM 'K:\DATAWAREHOUSEPROJECT\DATASETS\SOURCE_CRM\CUST_INFO.CSV'
WITH (
FIRSTROW=2,
FIELDTERMINATOR=',',
TABLOCK
);
GO
TRUNCATE TABLE BRONZE.CRM_PRD_INFO 
BULK INSERT BRONZE.CRM_PRD_INFO 
FROM 'K:\DATAWAREHOUSEPROJECT\DATASETS\SOURCE_CRM\PRD_INFO.CSV'
WITH (
FIRSTROW=2,
FIELDTERMINATOR=',',
TABLOCK
);
GO
TRUNCATE TABLE BRONZE.CRM_SALES_DETAILS
BULK INSERT BRONZE.CRM_SALES_DETAILS 
FROM 'K:\DATAWAREHOUSEPROJECT\DATASETS\SOURCE_CRM\SALES_DETAILS.CSV'
WITH (
FIRSTROW=2,
FIELDTERMINATOR=',',
TABLOCK
);
GO
TRUNCATE TABLE BRONZE.ERP_CUST_AZ12
BULK INSERT BRONZE.ERP_CUST_AZ12 
FROM 'K:\DATAWAREHOUSEPROJECT\DATASETS\SOURCE_ERP\CUST_AZ12.CSV'
WITH (
FIRSTROW=2,
FIELDTERMINATOR=',',
TABLOCK
);
GO
TRUNCATE TABLE BRONZE.ERP_LOC_A101 
BULK INSERT BRONZE.ERP_LOC_A101 
FROM 'K:\DATAWAREHOUSEPROJECT\DATASETS\SOURCE_ERP\LOC_A101.CSV'
WITH (
FIRSTROW=2,
FIELDTERMINATOR=',',
TABLOCK
);
GO
TRUNCATE TABLE BRONZE.ERP_PX_CAT_G1V2 
BULK INSERT BRONZE.ERP_PX_CAT_G1V2
FROM 'K:\DATAWAREHOUSEPROJECT\DATASETS\SOURCE_ERP\PX_CAT_G1V2.CSV'
WITH (
FIRSTROW=2,
FIELDTERMINATOR=',',
TABLOCK
);
